# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('ui', 'ui'), ('config', 'config'), ('data', 'data'), ('analyzer', 'analyzer'), ('monitor', 'monitor'), ('trader', 'trader'), ('config/logging_config.py', 'config'), ('.env', '.')],
    hiddenimports=[
        'streamlit',
        'streamlit.runtime',
        'streamlit.web',
        'streamlit.elements',
        'streamlit.delta_generator',
        'pandas',
        'numpy',
        'requests',
        'tushare',
        'urllib3',
        'charset_normalizer',
        'idna',
        'certifi',
        'click',
        'blinker',
        'packaging',
        'altair',
        'toolz',
        'jinja2',
        'markdown',
        'tenacity',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='AI_Stock_Monitor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
