workflows:
  default:
    name: Flutter Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build iOS IPA
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/Runner.ipa
